import { Employee } from '@/types/employee';
import { Site, JobType } from '@/types/site';
import { Shift } from '@/types/shift';
import { AttendanceRecord } from '@/types/attendance';
import { EmployeeLicence, ComplianceSummary } from '@/types/licence';
import { EmployeeDocument } from '@/types/document';

export const mockJobTypes: JobType[] = [
  {
    id: 'job-type-1',
    companyId: 'company-demo-1',
    name: 'SIA Door Supervisor',
    description: 'Front of house access control, customer safety, and venue security.',
    isActive: true,
    createdAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'job-type-2',
    companyId: 'company-demo-1',
    name: 'Static Security Guard',
    description: 'Perimeter patrol, surveillance monitoring, and building lock-down.',
    isActive: true,
    createdAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'job-type-3',
    companyId: 'company-demo-1',
    name: 'CCTV Operator',
    description: 'Control room surveillance, incident dispatch, and evidence logging.',
    isActive: true,
    createdAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'job-type-4',
    companyId: 'company-demo-1',
    name: 'Close Protection Officer',
    description: 'Executive security escort and VIP asset protection.',
    isActive: true,
    createdAt: '2025-01-10T08:00:00Z',
  },
];

export const mockSites: Site[] = [
  {
    id: 'site-demo-1',
    companyId: 'company-demo-1',
    name: 'Canary Wharf Tower A',
    code: 'LON-CW01',
    address: {
      line1: '25 Bank Street',
      city: 'London',
      postalCode: 'E14 5JP',
      country: 'United Kingdom',
    },
    contactName: 'Alistair Sterling',
    contactPhone: '+44 20 7946 0192',
    contactEmail: 'sterling@canarywharf-security.co.uk',
    status: 'active',
    configuredJobsCount: 2,
    jobs: [
      {
        id: 'sj-1',
        companyId: 'company-demo-1',
        siteId: 'site-demo-1',
        jobTypeId: 'job-type-1',
        defaultPayRate: 14.5,
        billingRate: 22.0,
        currency: 'GBP',
        status: 'active',
        jobType: mockJobTypes[0],
        createdAt: '2025-01-15T09:00:00Z',
      },
      {
        id: 'sj-2',
        companyId: 'company-demo-1',
        siteId: 'site-demo-1',
        jobTypeId: 'job-type-3',
        defaultPayRate: 16.0,
        billingRate: 25.5,
        currency: 'GBP',
        status: 'active',
        jobType: mockJobTypes[2],
        createdAt: '2025-01-15T09:00:00Z',
      },
    ],
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2025-01-15T09:00:00Z',
  },
  {
    id: 'site-demo-2',
    companyId: 'company-demo-1',
    name: 'Paddington Central Logistics Hub',
    code: 'LON-PAD02',
    address: {
      line1: '12 Kingdom Street',
      city: 'London',
      postalCode: 'W2 6BD',
      country: 'United Kingdom',
    },
    contactName: 'Hannah Davies',
    contactPhone: '+44 20 7946 0481',
    contactEmail: 'facilities@paddington-hub.co.uk',
    status: 'active',
    configuredJobsCount: 2,
    jobs: [
      {
        id: 'sj-3',
        companyId: 'company-demo-1',
        siteId: 'site-demo-2',
        jobTypeId: 'job-type-2',
        defaultPayRate: 13.75,
        billingRate: 20.5,
        currency: 'GBP',
        status: 'active',
        jobType: mockJobTypes[1],
        createdAt: '2025-01-16T10:00:00Z',
      },
    ],
    createdAt: '2025-01-16T10:00:00Z',
    updatedAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 'site-demo-3',
    companyId: 'company-demo-1',
    name: 'Stratford Westfield Retail Pavilion',
    code: 'LON-STF03',
    address: {
      line1: 'Montfichet Road, Olympic Park',
      city: 'London',
      postalCode: 'E20 1EJ',
      country: 'United Kingdom',
    },
    contactName: 'Julian Croft',
    contactPhone: '+44 20 7946 0773',
    contactEmail: 'operations@westfield-retail.co.uk',
    status: 'active',
    configuredJobsCount: 1,
    jobs: [
      {
        id: 'sj-4',
        companyId: 'company-demo-1',
        siteId: 'site-demo-3',
        jobTypeId: 'job-type-1',
        defaultPayRate: 15.0,
        billingRate: 23.5,
        currency: 'GBP',
        status: 'active',
        jobType: mockJobTypes[0],
        createdAt: '2025-01-18T11:00:00Z',
      },
    ],
    createdAt: '2025-01-18T11:00:00Z',
    updatedAt: '2025-01-18T11:00:00Z',
  },
  {
    id: 'site-demo-4',
    companyId: 'company-demo-1',
    name: 'Birmingham Colmore Business District',
    code: 'BIR-COL04',
    address: {
      line1: '103 Colmore Row',
      city: 'Birmingham',
      postalCode: 'B3 3AG',
      country: 'United Kingdom',
    },
    contactName: 'Rachel Thorne',
    contactPhone: '+44 121 496 0382',
    contactEmail: 'rachel.thorne@colmore-estate.co.uk',
    status: 'active',
    configuredJobsCount: 1,
    jobs: [
      {
        id: 'sj-5',
        companyId: 'company-demo-1',
        siteId: 'site-demo-4',
        jobTypeId: 'job-type-2',
        defaultPayRate: 13.5,
        billingRate: 20.0,
        currency: 'GBP',
        status: 'active',
        jobType: mockJobTypes[1],
        createdAt: '2025-01-20T12:00:00Z',
      },
    ],
    createdAt: '2025-01-20T12:00:00Z',
    updatedAt: '2025-01-20T12:00:00Z',
  },
];

export const mockEmployees: Employee[] = [
  {
    id: 'emp-demo-1',
    companyId: 'company-demo-1',
    employeeNumber: 'EMP-00101',
    firstName: 'Marcus',
    lastName: 'Vance',
    email: 'marcus.vance@workforce-demo.co.uk',
    phone: '+44 7700 900123',
    dateOfBirth: '1988-04-12',
    address: {
      line1: '42 Highbury Grove',
      city: 'London',
      postalCode: 'N5 2ER',
      country: 'United Kingdom',
    },
    emergencyContact: {
      name: 'Sarah Vance',
      relationship: 'Spouse',
      phone: '+44 7700 900456',
    },
    employmentStatus: 'active',
    employmentStartDate: '2023-03-01',
    licence: {
      id: 'lic-1',
      licenceType: 'SIA Door Supervisor',
      licenceNumber: '1014-9821-4402-9912',
      expiryDate: '2027-08-30',
      status: 'valid',
    },
    createdAt: '2023-03-01T08:00:00Z',
    updatedAt: '2023-03-01T08:00:00Z',
  },
  {
    id: 'emp-demo-2',
    companyId: 'company-demo-1',
    employeeNumber: 'EMP-00102',
    firstName: 'Elena',
    lastName: 'Rostova',
    email: 'elena.rostova@workforce-demo.co.uk',
    phone: '+44 7700 900345',
    dateOfBirth: '1992-09-18',
    address: {
      line1: '18 Richmond Way',
      city: 'London',
      postalCode: 'W12 8LE',
      country: 'United Kingdom',
    },
    emergencyContact: {
      name: 'Dmitri Rostov',
      relationship: 'Brother',
      phone: '+44 7700 900678',
    },
    employmentStatus: 'active',
    employmentStartDate: '2023-06-15',
    licence: {
      id: 'lic-2',
      licenceType: 'SIA CCTV Public Space',
      licenceNumber: '1022-7741-9031-1184',
      expiryDate: '2026-11-14',
      status: 'valid',
    },
    createdAt: '2023-06-15T08:00:00Z',
    updatedAt: '2023-06-15T08:00:00Z',
  },
  {
    id: 'emp-demo-3',
    companyId: 'company-demo-1',
    employeeNumber: 'EMP-00103',
    firstName: 'David',
    lastName: 'O’Connor',
    email: 'david.oconnor@workforce-demo.co.uk',
    phone: '+44 7700 900789',
    dateOfBirth: '1985-11-05',
    address: {
      line1: '89 Greenwich South Street',
      city: 'London',
      postalCode: 'SE10 8NX',
      country: 'United Kingdom',
    },
    emergencyContact: {
      name: 'Claire O’Connor',
      relationship: 'Spouse',
      phone: '+44 7700 900112',
    },
    employmentStatus: 'active',
    employmentStartDate: '2022-09-01',
    licence: {
      id: 'lic-3',
      licenceType: 'SIA Security Guard',
      licenceNumber: '1030-4412-8820-3391',
      expiryDate: '2026-10-20',
      status: 'expiring_soon',
    },
    createdAt: '2022-09-01T08:00:00Z',
    updatedAt: '2022-09-01T08:00:00Z',
  },
  {
    id: 'emp-demo-4',
    companyId: 'company-demo-1',
    employeeNumber: 'EMP-00104',
    firstName: 'Tariq',
    lastName: 'Mansoor',
    email: 'tariq.mansoor@workforce-demo.co.uk',
    phone: '+44 7700 900223',
    dateOfBirth: '1995-02-28',
    address: {
      line1: '74 Commercial Road',
      city: 'London',
      postalCode: 'E1 1LP',
      country: 'United Kingdom',
    },
    emergencyContact: {
      name: 'Zainab Mansoor',
      relationship: 'Mother',
      phone: '+44 7700 900445',
    },
    employmentStatus: 'probation',
    employmentStartDate: '2024-01-10',
    licence: {
      id: 'lic-4',
      licenceType: 'SIA Door Supervisor',
      licenceNumber: '1044-6632-1109-8874',
      expiryDate: '2027-04-12',
      status: 'valid',
    },
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 'emp-demo-5',
    companyId: 'company-demo-1',
    employeeNumber: 'EMP-00105',
    firstName: 'Chloe',
    lastName: 'Jenkins',
    email: 'chloe.jenkins@workforce-demo.co.uk',
    phone: '+44 7700 900889',
    dateOfBirth: '1990-07-22',
    address: {
      line1: '15 Victoria Square',
      city: 'Birmingham',
      postalCode: 'B1 1BD',
      country: 'United Kingdom',
    },
    emergencyContact: {
      name: 'Tom Jenkins',
      relationship: 'Father',
      phone: '+44 7700 900998',
    },
    employmentStatus: 'active',
    employmentStartDate: '2023-11-01',
    licence: {
      id: 'lic-5',
      licenceType: 'SIA Security Guard',
      licenceNumber: '1051-2299-4411-6633',
      expiryDate: '2027-02-15',
      status: 'valid',
    },
    createdAt: '2023-11-01T08:00:00Z',
    updatedAt: '2023-11-01T08:00:00Z',
  },
];

export const getTodayDateString = () => {
  return new Date().toISOString().split('T')[0];
};

export const mockShifts: Shift[] = [
  {
    id: 'shift-demo-1',
    companyId: 'company-demo-1',
    siteId: 'site-demo-1',
    siteJobId: 'sj-1',
    employeeId: 'emp-demo-1',
    shiftDate: getTodayDateString(),
    startTime: '07:00',
    endTime: '19:00',
    breakMinutes: 45,
    status: 'in_progress',
    notes: 'Main lobby entrance access control and bag scanning.',
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2025-01-20T08:00:00Z',
    site: mockSites[0],
    siteJob: mockSites[0].jobs?.[0],
    employee: mockEmployees[0],
  },
  {
    id: 'shift-demo-2',
    companyId: 'company-demo-1',
    siteId: 'site-demo-1',
    siteJobId: 'sj-2',
    employeeId: 'emp-demo-2',
    shiftDate: getTodayDateString(),
    startTime: '08:00',
    endTime: '20:00',
    breakMinutes: 60,
    status: 'in_progress',
    notes: 'Control Room primary operator. Monitor CCTV and alarm triggers.',
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2025-01-20T08:00:00Z',
    site: mockSites[0],
    siteJob: mockSites[0].jobs?.[1],
    employee: mockEmployees[1],
  },
  {
    id: 'shift-demo-3',
    companyId: 'company-demo-1',
    siteId: 'site-demo-2',
    siteJobId: 'sj-3',
    employeeId: 'emp-demo-3',
    shiftDate: getTodayDateString(),
    startTime: '06:00',
    endTime: '18:00',
    breakMinutes: 30,
    status: 'completed',
    notes: 'Logistics bay gate security and vehicle entry permits.',
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2025-01-20T08:00:00Z',
    site: mockSites[1],
    siteJob: mockSites[1].jobs?.[0],
    employee: mockEmployees[2],
  },
  {
    id: 'shift-demo-4',
    companyId: 'company-demo-1',
    siteId: 'site-demo-3',
    siteJobId: 'sj-4',
    employeeId: 'emp-demo-4',
    shiftDate: getTodayDateString(),
    startTime: '19:00',
    endTime: '07:00',
    breakMinutes: 60,
    status: 'scheduled',
    notes: 'Overnight retail perimeter patrol and emergency lockup.',
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2025-01-20T08:00:00Z',
    site: mockSites[2],
    siteJob: mockSites[2].jobs?.[0],
    employee: mockEmployees[3],
  },
  {
    id: 'shift-demo-5',
    companyId: 'company-demo-1',
    siteId: 'site-demo-4',
    siteJobId: 'sj-5',
    employeeId: 'emp-demo-5',
    shiftDate: getTodayDateString(),
    startTime: '08:30',
    endTime: '17:30',
    breakMinutes: 45,
    status: 'in_progress',
    notes: 'Commercial reception guard and visitor pass management.',
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2025-01-20T08:00:00Z',
    site: mockSites[3],
    siteJob: mockSites[3].jobs?.[0],
    employee: mockEmployees[4],
  },
];

export const mockAttendanceRecords: AttendanceRecord[] = [
  {
    id: 'att-demo-1',
    companyId: 'company-demo-1',
    shiftId: 'shift-demo-1',
    employeeId: 'emp-demo-1',
    siteId: 'site-demo-1',
    clockInTime: `${getTodayDateString()}T06:55:00Z`,
    clockInLat: 51.5033,
    clockInLng: -0.0195,
    clockInAccuracy: 8,
    clockInDistance: 12,
    clockInVerified: true,
    clockOutVerified: false,
    breakMinutes: 0,
    totalHours: 4.5,
    status: 'clocked_in',
    varianceFlag: 'none',
    supervisorNotes: 'Arrived 5 mins early. Handover from night supervisor complete.',
    createdAt: `${getTodayDateString()}T06:55:00Z`,
    updatedAt: `${getTodayDateString()}T06:55:00Z`,
    employee: mockEmployees[0],
    site: mockSites[0],
    shift: mockShifts[0],
  },
  {
    id: 'att-demo-2',
    companyId: 'company-demo-1',
    shiftId: 'shift-demo-2',
    employeeId: 'emp-demo-2',
    siteId: 'site-demo-1',
    clockInTime: `${getTodayDateString()}T07:58:00Z`,
    clockInLat: 51.5034,
    clockInLng: -0.0194,
    clockInAccuracy: 6,
    clockInDistance: 15,
    clockInVerified: true,
    clockOutVerified: false,
    breakStartTime: `${getTodayDateString()}T12:00:00Z`,
    breakMinutes: 30,
    totalHours: 3.5,
    status: 'on_break',
    varianceFlag: 'none',
    supervisorNotes: 'Midday meal break taken as scheduled.',
    createdAt: `${getTodayDateString()}T07:58:00Z`,
    updatedAt: `${getTodayDateString()}T12:00:00Z`,
    employee: mockEmployees[1],
    site: mockSites[0],
    shift: mockShifts[1],
  },
  {
    id: 'att-demo-3',
    companyId: 'company-demo-1',
    shiftId: 'shift-demo-3',
    employeeId: 'emp-demo-3',
    siteId: 'site-demo-2',
    clockInTime: `${getTodayDateString()}T05:50:00Z`,
    clockOutTime: `${getTodayDateString()}T18:05:00Z`,
    clockInLat: 51.5175,
    clockInLng: -0.1782,
    clockInAccuracy: 10,
    clockInDistance: 22,
    clockInVerified: true,
    clockOutLat: 51.5176,
    clockOutLng: -0.1781,
    clockOutAccuracy: 9,
    clockOutDistance: 18,
    clockOutVerified: true,
    breakMinutes: 30,
    totalHours: 11.75,
    status: 'reconciled',
    varianceFlag: 'none',
    supervisorNotes: 'Shift complete and reconciled without variance.',
    reconciledBy: 'Supervisor Smith',
    reconciledAt: `${getTodayDateString()}T18:10:00Z`,
    createdAt: `${getTodayDateString()}T05:50:00Z`,
    updatedAt: `${getTodayDateString()}T18:10:00Z`,
    employee: mockEmployees[2],
    site: mockSites[1],
    shift: mockShifts[2],
  },
  {
    id: 'att-demo-4',
    companyId: 'company-demo-1',
    shiftId: 'shift-demo-5',
    employeeId: 'emp-demo-5',
    siteId: 'site-demo-4',
    clockInTime: `${getTodayDateString()}T08:42:00Z`,
    clockInLat: 52.4801,
    clockInLng: -1.8985,
    clockInAccuracy: 12,
    clockInDistance: 28,
    clockInVerified: true,
    clockOutVerified: false,
    breakMinutes: 0,
    totalHours: 2.8,
    status: 'clocked_in',
    varianceFlag: 'late_arrival',
    supervisorNotes: 'Traffic delay on M6; notified operations supervisor in advance.',
    createdAt: `${getTodayDateString()}T08:42:00Z`,
    updatedAt: `${getTodayDateString()}T08:42:00Z`,
    employee: mockEmployees[4],
    site: mockSites[3],
    shift: mockShifts[4],
  },
];

export const mockLicences: EmployeeLicence[] = [
  {
    id: 'lic-demo-1',
    companyId: 'company-demo-1',
    employeeId: 'emp-demo-1',
    licenceType: 'SIA Door Supervisor',
    licenceNumber: '1002938475610293',
    expiryDate: '2027-04-15',
    status: 'valid',
    verifiedAt: '2025-01-15T10:00:00Z',
    verifiedBy: 'Operations Manager',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    employee: mockEmployees[0],
  },
  {
    id: 'lic-demo-2',
    companyId: 'company-demo-1',
    employeeId: 'emp-demo-2',
    licenceType: 'SIA CCTV Surveillance',
    licenceNumber: '2093847561029384',
    expiryDate: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'expiring_soon',
    verifiedAt: '2025-01-16T11:00:00Z',
    verifiedBy: 'Operations Manager',
    createdAt: '2025-01-16T11:00:00Z',
    updatedAt: '2025-01-16T11:00:00Z',
    employee: mockEmployees[1],
  },
  {
    id: 'lic-demo-3',
    companyId: 'company-demo-1',
    employeeId: 'emp-demo-3',
    licenceType: 'SIA Security Guard',
    licenceNumber: '3094857610293847',
    expiryDate: '2027-09-30',
    status: 'valid',
    verifiedAt: '2025-01-17T09:30:00Z',
    verifiedBy: 'Operations Manager',
    createdAt: '2025-01-17T09:30:00Z',
    updatedAt: '2025-01-17T09:30:00Z',
    employee: mockEmployees[2],
  },
  {
    id: 'lic-demo-4',
    companyId: 'company-demo-1',
    employeeId: 'emp-demo-4',
    licenceType: 'SIA Close Protection',
    licenceNumber: '4095867120394857',
    expiryDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'expired',
    verifiedAt: '2024-02-10T12:00:00Z',
    verifiedBy: 'Compliance Lead',
    createdAt: '2024-02-10T12:00:00Z',
    updatedAt: '2025-01-18T10:00:00Z',
    employee: mockEmployees[3],
  },
  {
    id: 'lic-demo-5',
    companyId: 'company-demo-1',
    employeeId: 'emp-demo-5',
    licenceType: 'SIA Door Supervisor',
    licenceNumber: '5096871230495867',
    expiryDate: '2026-11-20',
    status: 'pending_verification',
    createdAt: '2025-02-01T14:20:00Z',
    updatedAt: '2025-02-01T14:20:00Z',
    employee: mockEmployees[4],
  },
];

export const mockDocuments: EmployeeDocument[] = [
  {
    id: 'doc-demo-1',
    companyId: 'company-demo-1',
    employeeId: 'emp-demo-1',
    documentType: 'RightToWork',
    fileName: 'british_passport_scan.pdf',
    storagePath: 'company-demo-1/emp-demo-1/passport.pdf',
    mimeType: 'application/pdf',
    fileSizeBytes: 2450000,
    isVerified: true,
    verifiedAt: '2025-01-15T10:00:00Z',
    verifiedBy: 'Operations Manager',
    createdAt: '2025-01-15T09:30:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'doc-demo-2',
    companyId: 'company-demo-1',
    employeeId: 'emp-demo-1',
    documentType: 'SIA_Badge_Scan',
    fileName: 'sia_door_supervisor_front_back.png',
    storagePath: 'company-demo-1/emp-demo-1/sia_badge.png',
    mimeType: 'image/png',
    fileSizeBytes: 1200000,
    isVerified: true,
    verifiedAt: '2025-01-15T10:05:00Z',
    verifiedBy: 'Operations Manager',
    createdAt: '2025-01-15T09:35:00Z',
    updatedAt: '2025-01-15T10:05:00Z',
  },
  {
    id: 'doc-demo-3',
    companyId: 'company-demo-1',
    employeeId: 'emp-demo-2',
    documentType: 'ProofOfAddress',
    fileName: 'council_tax_statement_2025.pdf',
    storagePath: 'company-demo-1/emp-demo-2/proof_of_address.pdf',
    mimeType: 'application/pdf',
    fileSizeBytes: 890000,
    isVerified: false,
    createdAt: '2025-01-16T11:00:00Z',
    updatedAt: '2025-01-16T11:00:00Z',
  },
];

export const mockComplianceSummary: ComplianceSummary = {
  total: 5,
  valid: 2,
  expiringSoon: 1,
  expired: 1,
  pendingVerification: 1,
  rejected: 0,
};

